In [1]:
import pandas as pd

In [2]:
wind=pd.read_csv("https://raw.githubusercontent.com/nikhilpodila/Classification-UCI-Datasets/master/winequality-red.csv", sep=";")

In [3]:
wind.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
X=wind.drop('quality', axis=1)
Y=wind['quality']
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=0)

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)

RandomForestClassifier()

In [8]:
Y_pred = model.predict(X_test)

In [10]:
result = pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred})
result

      Actual  Predicted
1109       6          6
1032       5          5
1002       7          7
487        6          5
979        5          5
...      ...        ...
489        6          6
362        5          5
526        5          5
442        7          5
1229       5          5

[400 rows x 2 columns]

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))

[[  0   0   0   2   0   0]
 [  0   0   9   5   0   0]
 [  0   0 129  37   3   0]
 [  0   0  34 122  14   0]
 [  0   0   3  12  23   2]
 [  0   0   0   2   3   0]]
0.685

In [ ]:
# Excercise -2  (RandomForest)

In [12]:
inds = pd.read_csv("https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv", header=None)

In [13]:
inds.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [20]:
col = []
for i in range(0,35):
    col.append("IP" + str(i))
print(col)

['IP0', 'IP1', 'IP2', 'IP3', 'IP4', 'IP5', 'IP6', 'IP7', 'IP8', 'IP9', 'IP10', 'IP11', 'IP12', 'IP13', 'IP14', 'IP15', 'IP16', 'IP17', 'IP18', 'IP19', 'IP20', 'IP21', 'IP22', 'IP23', 'IP24', 'IP25', 'IP26', 'IP27', 'IP28', 'IP29', 'IP30', 'IP31', 'IP32', 'IP33', 'IP34']

In [23]:
inds.columns=col
inds.head()

,IP0,IP1,IP2,IP3,IP4,IP5,IP6,IP7,IP8,IP9,...,IP25,IP26,IP27,IP28,IP29,IP30,IP31,IP32,IP33,IP34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [24]:
X=inds.drop('IP34',axis=1)
Y=inds['IP34']

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=0)

In [27]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
result = pd.DataFrame({"Actual": Y_test, "Predicted": Y_pred})
result

    Actual Predicted
6        g         g
52       g         b
114      b         b
45       b         b
106      b         b
..     ...       ...
100      b         b
22       g         g
162      b         b
332      g         g
141      g         g

[88 rows x 2 columns]

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))

[[36  2]
 [ 1 49]]
0.9659090909090909